export const transporters = [
  {
    id: 1,
    name: "TIDJINI Tidjini",
    localisation: {
      user: 1,
      longitude: -0.6337376,
      latitude: 35.6976541,
    },
    last_login: null,
    username: "tidjini",
    nom: "tidjini",
    prenom: "tidjini",
    sex: 1,
    is_admin: true,
    is_active: true,
    is_staff: true,
    is_superuser: true,
    photo: null,
    telephone: null,
    telephone_deux: null,
    date_naissance: null,
    database_name: null,
    exercice: null,
  },
  {
    id: 2,
    name: "IMAD Imad",
    localisation: {
      user: 2,
      longitude: -0.64,
      latitude: 35.6976141,
    },
    last_login: null,
    username: "imad",
    nom: "imad",
    prenom: "imad",
    sex: 1,
    is_admin: true,
    is_active: true,
    is_staff: true,
    is_superuser: true,
    photo: null,
    telephone: "  ",
    telephone_deux: null,
    date_naissance: null,
    database_name: null,
    exercice: null,
  },
  {
    id: 3,
    name: "WAHIBA Wahiba",
    localisation: {
      user: 2,
      longitude: -0.74,
      latitude: 35.6976141,
    },
    last_login: null,
    username: "wahiba",
    nom: "wahiba",
    prenom: "wahiba",
    sex: 1,
    is_admin: false,
    is_active: true,
    is_staff: false,
    is_superuser: false,
    photo: null,
    telephone: null,
    telephone_deux: null,
    date_naissance: null,
    database_name: null,
    exercice: null,
  },
  {
    id: 4,
    name: "ARSLAN Arslan",
    localisation: {
      user: 2,
      longitude: -0.74,
      latitude: 35.8,
    },
    last_login: null,
    username: "arslan",
    nom: "arslan",
    prenom: "arslan",
    sex: 1,
    is_admin: false,
    is_active: true,
    is_staff: false,
    is_superuser: false,
    photo: null,
    telephone: null,
    telephone_deux: null,
    date_naissance: null,
    database_name: null,
    exercice: null,
  },
  {
    id: 5,
    name: "CHAFIK Chafik",
    localisation: null,
    last_login: null,
    username: "chafik",
    nom: "chafik",
    prenom: "chafik",
    sex: 1,
    is_admin: false,
    is_active: true,
    is_staff: false,
    is_superuser: false,
    photo: null,
    telephone: null,
    telephone_deux: null,
    date_naissance: null,
    database_name: null,
    exercice: null,
  },
  {
    id: 6,
    name: "SAFA Safa",
    localisation: null,
    last_login: null,
    username: "safa",
    nom: "safa",
    prenom: "safa",
    sex: 1,
    is_admin: false,
    is_active: true,
    is_staff: false,
    is_superuser: false,
    photo: null,
    telephone: null,
    telephone_deux: null,
    date_naissance: null,
    database_name: null,
    exercice: null,
  },
  {
    id: 7,
    name: "HACHEMI Hachemi",
    localisation: null,
    last_login: null,
    username: "hachemi",
    nom: "hachemi",
    prenom: "hachemi",
    sex: 1,
    is_admin: false,
    is_active: true,
    is_staff: false,
    is_superuser: false,
    photo: null,
    telephone: null,
    telephone_deux: null,
    date_naissance: null,
    database_name: null,
    exercice: null,
  },
  {
    id: 8,
    name: "YAHIA Yahia",
    localisation: null,
    last_login: null,
    username: "yahia",
    nom: "yahia",
    prenom: "yahia",
    sex: 1,
    is_admin: false,
    is_active: true,
    is_staff: false,
    is_superuser: false,
    photo: null,
    telephone: null,
    telephone_deux: null,
    date_naissance: null,
    database_name: null,
    exercice: null,
  },
  {
    id: 9,
    name: "IKRAM Ikram",
    localisation: null,
    last_login: null,
    username: "ikram",
    nom: "ikram",
    prenom: "ikram",
    sex: 1,
    is_admin: false,
    is_active: true,
    is_staff: false,
    is_superuser: false,
    photo: null,
    telephone: null,
    telephone_deux: null,
    date_naissance: null,
    database_name: null,
    exercice: null,
  },
  {
    id: 10,
    name: "DJAMEL Djamel",
    localisation: null,
    last_login: null,
    username: "djamel",
    nom: "djamel",
    prenom: "djamel",
    sex: 1,
    is_admin: false,
    is_active: true,
    is_staff: false,
    is_superuser: false,
    photo: null,
    telephone: null,
    telephone_deux: null,
    date_naissance: null,
    database_name: null,
    exercice: null,
  },
  {
    id: 11,
    name: "OTHMAN Othman",
    localisation: null,
    last_login: null,
    username: "othman",
    nom: "othman",
    prenom: "othman",
    sex: 1,
    is_admin: false,
    is_active: true,
    is_staff: false,
    is_superuser: false,
    photo: null,
    telephone: null,
    telephone_deux: null,
    date_naissance: null,
    database_name: null,
    exercice: null,
  },
  {
    id: 12,
    name: "RACHID Rachid",
    localisation: null,
    last_login: null,
    username: "rachid",
    nom: "rachid",
    prenom: "rachid",
    sex: 1,
    is_admin: false,
    is_active: true,
    is_staff: false,
    is_superuser: false,
    photo: null,
    telephone: null,
    telephone_deux: null,
    date_naissance: null,
    database_name: null,
    exercice: null,
  },
  {
    id: 13,
    name: "LAHCEN Lahcen",
    localisation: null,
    last_login: null,
    username: "lahcen",
    nom: "lahcen",
    prenom: "lahcen",
    sex: 1,
    is_admin: false,
    is_active: true,
    is_staff: false,
    is_superuser: false,
    photo: null,
    telephone: null,
    telephone_deux: null,
    date_naissance: null,
    database_name: null,
    exercice: null,
  },
  {
    id: 14,
    name: "NOURDIN Nourdin",
    localisation: null,
    last_login: null,
    username: "nourdin",
    nom: "nourdin",
    prenom: "nourdin",
    sex: 1,
    is_admin: false,
    is_active: true,
    is_staff: false,
    is_superuser: false,
    photo: null,
    telephone: null,
    telephone_deux: null,
    date_naissance: null,
    database_name: null,
    exercice: null,
  },
];

export const localisations = [
  {
    id: 1,
    task: 21,
    origin_address: "Origin",
    origin_lng: -0.74,
    origin_lat: 35.6976141,
    destination_address: "Destination",
    destination_lng: -0.6,
    destination_lat: 35.2,
  },
  {
    id: 2,
    task: 21,
    origin_address: "Origin",
    origin_lng: -0.74,
    origin_lat: 35.6976141,
    destination_address: "Destination",
    destination_lng: -0.6,
    destination_lat: 35.2,
  },
  {
    id: 3,
    task: 22,
    origin_address: "Origin",
    origin_lng: -0.74,
    origin_lat: 35.6976141,
    destination_address: "Destination",
    destination_lng: -0.6,
    destination_lat: 35.2,
  },
];
