export const RESPONSABLE_COLLECTION = "[PRODUCTION-RESPONSABLE] COLLECTION";
export const LOADING = "[PRODUCTION-RESPONSABLE] LOADING";
export const ERROR = "[PRODUCTION-RESPONSABLE] COLLECTION ERROR";
