const states = ["happy", "cool", "normal", "bored", "annoyed", "very_annoyed"];
const states_tache = ["en cours", "termine", "pause"];

export const data = {
  count: 7,
  next: null,
  previous: null,
  results: [],
};

export const taches = {
  count: 7,
  next: null,
  previous: null,
  results: [
    {
      id: "1",
      task: "Démo",
      sex: 1,
      descrpition: "Démonstration de cette application ou autre chose",
      time: "15h - 16h30",
      persone: "Messaoudi Tidjini",
      retard: true,
      state: states_tache[2],
      acheve: false,
    },
    {
      id: "2",
      task: "Autre",
      descrpition: "Démonstration de cette application ou autre chose",
      time: "15h - 16h30",
      sex: 2,
      persone: "Wahiba Hamada",
      retard: false,
      state: states_tache[1],
      acheve: true,
    },
    {
      id: "3",
      task: "Autre",
      descrpition: "Démonstration de cette application ou autre chose",
      time: "15h - 16h30",
      sex: 2,
      persone: "Wahiba Hamada",
      retard: true,
      state: states_tache[1],
      acheve: false,
    },

    {
      id: "4",
      task: "Autre",
      descrpition: "Démonstration de cette application ou autre chose",
      time: "15h - 16h30",
      sex: 1,
      persone: "Amine Ibrahim",
      retard: true,
      state: states_tache[0],
      acheve: false,
    },
    {
      id: "5",
      task: "Tâche",
      descrpition: "Démonstration de cette application ou autre chose",
      time: "15h - 16h30",
      sex: 1,
      persone: "Amine Ibrahim",
      retard: true,
      state: states_tache[2],
      acheve: true,
    },
    {
      id: "6",
      task: "Task",
      descrpition: "Démonstration de cette application ou autre chose..",
      time: "15h - 16h30",
      sex: 1,
      persone: "Moussa Amine",
      retard: false,
      state: states_tache[2],
      acheve: false,
    },
    {
      id: "7",
      task: "Task",
      descrpition: "Démonstration de cette application ou autre chose....",
      time: "15h - 16h30",
      sex: 1,
      persone: "Moussa Amine",
      retard: false,
      state: states_tache[1],
      acheve: true,
    },
  ],
};
