export const RESPONSABLE_COLLECTION = "[EXPEDITION-RESPONSABLE] COLLECTION";
export const LOADING = "[EXPEDITION-RESPONSABLE] LOADING";
export const ERROR = "[EXPEDITION-RESPONSABLE] COLLECTION ERROR";
