export const collectionStyles = {
  container: {
    padding: "10px 32px",
    display: "flex",
    flexDirection: "row",
    minHeight: "100%",
    position: "relative",
    flex: "1 1 auto",
    height: "100%",
  },
  container_l1: {
    display: "flex",
    flexDirection: "column",
    padding: "0 1.2rem",
    flex: "1 1 100%",
    zIndex: 2,
    maxWidth: "100%",
    minWidth: 0,
    minHeight: 0,
  },
  table_container: {
    display: "flex",
    flex: "1 1 100%",
    flexDirection: "column",
    minHeight: 0,
    borderRadius: "8px 8px 0 0",
    marginTop: 10,
    marginBottom: 10,
  },
  loading_container: {
    display: "flex",
    backgroundColor: "#26465330",
    position: "absolute",
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifycontent: "center",
    zIndex: 500,
  },
  header: { padding: "10px 0 20px 0" },
  titleContainer: { display: "flex", alignItems: "center" },
  title: { fontSize: 24, fontWeight: "bold" },
  titleSpan: { fontWeight: "400" },
  description: { fontSize: 12, color: "#8D8F9D", fontWeight: "600" },
  icon: {
    width: 32,
    height: 32,
    marginRight: 16,
  },

  divider: {
    height: 0.8,
    width: "100%",
    marginBottom: 20,
  },
};
