export const CATEGORIE_COLLECTION = "[CATEGORIE] COLLECTION";
export const LOADING = "[CATEGORIE] LOADING";
export const ERROR = "[CATEGORIE] COLLECTION ERROR";
export const SAVE = "[CATEGORIE] SAVE";
export const SAVE_ERROR = "[CATEGORIE] SAVE ERROR";
export const DELETE = "[CATEGORIE] DELETE";
export const DELETE_ERROR = "[CATEGORIE] DELETE ERROR";
