export const TACHE_CATEGORIE_COLLECTION = "[TACHE-CATEGORIE] COLLECTION";
export const TACHE_STATUE_COLLECTION = "[TACHE-STATUE] COLLECTION";
export const TACHE_URGENCE_COLLECTION = "[TACHE-URGENCE] COLLECTION";
export const TACHE_COLLECTION = "[TACHE] COLLECTION";
export const TACHE_RETRIEVE = "[TACHE] RETRIEVE";
export const GESTION_EMPLOYE_COLLECTION = "[GESTION-EMPLOYE] COLLECTION";
