export const SERVICE_COLLECTION = "[SERVICE-GRH] COLLECTION";
export const LOADING = "[SERVICE-GRH] LOADING";
export const ERROR = "[SERVICE-GRH] COLLECTION ERROR";
export const SAVE = "[SERVICE-GRH] SAVE";
export const SAVE_ERROR = "[SERVICE-GRH] SAVE ERROR";
export const DELETE = "[SERVICE-GRH] DELETE";
export const DELETE_ERROR = "[SERVICE-GRH] DELETE ERROR";
